name: Publish Go Binary

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GOACTION }}      
jobs:
  buildAndDeploy:
    runs-on:  ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # 交叉构建，多平台交叉编译
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
    # 使用checkout
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
        go-version: '>=1.23.6'
    - run:
       go version
    
    - name: Build
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          go build -o JudgeMore_Server-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        else
          go build -o JudgeMore_Server-${{ matrix.goos }}-${{ matrix.goarch }}
        fi
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}    
        
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: JudgeMore_Server-${{ matrix.goos }}-${{ matrix.goarch }}
        path: JudgeMore_Server-${{ matrix.goos }}-${{ matrix.goarch }}*
